### ISSUE TITLE
error after uploading files 

### ISSUE THREAD

**Issue by gerym77** [MeetanshiInc/Magento-Security-Patches-PrePatched-Files#1]
hello, 
after uploading files from patch 11086 I get this error message in backend and frontend

Magento Version 1.9.3.8
patch used: SUPEE-11086-1.9.3.10

Warning: include_once(phpseclib/bootstrap.php): failed to open stream: No such file or directory in /var/customers/webs/rossi/shop6/app/Mage.php on line 56 Warning: include_once(): Failed opening 'phpseclib/bootstrap.php' for inclusion (include_path='/var/customers/webs/rossi/shop6/app/code/local:/var/customers/webs/rossi/shop6/app/code/community:/var/customers/webs/rossi/shop6/app/code/core:/var/customers/webs/rossi/shop6/lib:.:/usr/share/php/:/usr/share/php5/') in /var/customers/webs/rossi/shop6/app/Mage.php on line 56 Warning: include_once(mcryptcompat/mcrypt.php): failed to open stream: No such file or directory in /var/customers/webs/rossi/shop6/app/Mage.php on line 57 Warning: include_once(): Failed opening 'mcryptcompat/mcrypt.php' for inclusion (include_path='/var/customers/webs/rossi/shop6/app/code/local:/var/customers/webs/rossi/shop6/app/code/community:/var/customers/webs/rossi/shop6/app/code/core:/var/customers/webs/rossi/shop6/lib:.:/usr/share/php/:/usr/share/php5/') in /var/customers/webs/rossi/shop6/app/Mage.php on line 57

can you help me on that please

many thanks

Gery

**Comment by shivbhadrasinhgohil** [comment]
Hi Gery,

You have used the Patch for 1.9.3.10 for your Magento 1.9.3.8 and that's why you faced the issue. 
Please use download the lib.zip file from here: https://cl.ly/c9fc39
Extract it and upload in the root of your Magento. 
This will fix the issue. 

Regards,
Shivbhadrasinh

**Comment by gerym77** [comment]
Hi Shivbhadrasinh,

many thanks for the great support..
this worked out fine!

**Comment by shivbhadrasinhgohil** [comment]
Awesome :)
